### ISSUE TITLE
xso: clear out cruft

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#279]
The xso module is really old and has accumulated quite some cruft. The following things stand out:

* [x] The documentation needs a makeover, with a more structured approach now that we’ve settled on terminology ("descriptor", "element type", "cdata type", …). (#302)
* [x] Some identifiers need fixing (``unparse_to_sax``) (#300)
* [x] There is a hard lxml dependency in there which is only needed for unittesting (``unparse_to_node``). The function should move to testutils or even into the tests directory to remove the lxml runtime dependency. (#281)
