### ISSUE TITLE
Modern IM: The grand picture

### ISSUE THREAD

**Issue by horazont** [horazont/aioxmpp#72]
This is what I envision for the support of modern instant messaging use-cases for aioxmpp. The core part of this is an abstract, unified interface to interact with other entities, to be able to re-use as much code as possible. We will call that interface AbstractConversation for now, even though it may consist of more than that.

* [ ] The AbstractConversation should be able to cover basic interaction in one-on-one chats, MUCs and MIXes, without knowing which of those is specifically used. Quirks must be abstracted away if possible and if not, announced in a portable manner (see #70).
* [ ] Support for querying MAM and synchronising MAM into local storage defined by the application (see #40 + later tracking PR).
* [ ] Support for Chat States (see #49 + later tracking PR).
* [ ] Support tracking via Message Delivery Notifications
* [ ] Support for Chat Markers (see #71)

Please add things you think make sense.

Not all of this will end up in the v0.9 release, but some of it will (see #70). I want this done for v1.0 (even though maybe without MIX support depending on the existance of servers and such).

**Comment by horazont** [comment]
Things like chat states, archive management (to a certain degree) should be implemented in Mixins, separate classes which integrate nicely with AbstractConversation or in the AbstractConversation baseclass itself, so that different implementations can re-use those.
